# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=31)),
                ('first_name', models.CharField(blank=True, max_length=31)),
                ('last_name', models.CharField(blank=True, max_length=31)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('frequency', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookshelfEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=31)),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(default='', max_length=128)),
                ('start_date', models.CharField(default='', max_length=128)),
                ('end_date', models.CharField(default='', max_length=128)),
                ('contract_type', models.CharField(default='', max_length=128)),
                ('contract_class', models.CharField(default='', max_length=128)),
                ('due_data', models.CharField(default='', max_length=128)),
                ('amount_money', models.CharField(default='', max_length=128)),
                ('auto_extensions', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href_to_image', models.CharField(default='', max_length=1024)),
                ('text', models.CharField(default='', max_length=512)),
                ('date', models.CharField(default='', max_length=32)),
                ('href_fb_post', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.CharField(default='', max_length=32)),
                ('type', models.CharField(default='', max_length=256)),
                ('icon', models.CharField(default='', max_length=256)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('age', models.CharField(default='', max_length=12)),
                ('gender', models.CharField(default='', max_length=32)),
                ('relation', models.CharField(default='', max_length=64)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('name_url', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=32)),
                ('type', models.CharField(default='', max_length=128)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('frequency', models.CharField(default='', max_length=64)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('example_image', models.CharField(default='', max_length=1024)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_access_token', models.CharField(default='', max_length=512)),
                ('lfd_id', models.CharField(blank=True, max_length=12)),
                ('parent_lfd_id', models.CharField(blank=True, max_length=12)),
                ('pnr_nr', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(blank=True, max_length=12)),
                ('given_name', models.CharField(blank=True, max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('email_address', models.CharField(blank=True, max_length=256)),
                ('browser_user_agent', models.CharField(blank=True, max_length=512)),
                ('telephone_number', models.CharField(blank=True, max_length=64)),
                ('telephone_country_code', models.CharField(blank=True, max_length=12)),
                ('birthday', models.CharField(blank=True, max_length=24)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('tropical_zodiac', models.CharField(blank=True, max_length=64)),
                ('cc_type', models.CharField(blank=True, max_length=64)),
                ('cc_number', models.CharField(blank=True, max_length=64)),
                ('cvv2', models.CharField(blank=True, max_length=12)),
                ('cc_expires', models.CharField(blank=True, max_length=64)),
                ('occupation', models.CharField(blank=True, max_length=256)),
                ('company', models.CharField(blank=True, max_length=256)),
                ('vehicle', models.CharField(blank=True, max_length=256)),
                ('domain', models.CharField(blank=True, max_length=256)),
                ('blood_type', models.CharField(blank=True, max_length=12)),
                ('pounds', models.CharField(blank=True, max_length=12)),
                ('kilograms', models.CharField(blank=True, max_length=12)),
                ('feet_inches', models.CharField(blank=True, max_length=12)),
                ('centimeters', models.CharField(blank=True, max_length=3)),
                ('profile_picture', models.CharField(blank=True, max_length=512)),
                ('maried', models.CharField(blank=True, max_length=64)),
                ('kids', models.CharField(blank=True, max_length=12)),
                ('income', models.CharField(blank=True, max_length=64)),
                ('expenses', models.CharField(blank=True, max_length=64)),
                ('fitness', models.CharField(blank=True, max_length=128)),
                ('activities', models.CharField(blank=True, max_length=512)),
                ('home_town', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('education', models.CharField(blank=True, max_length=256)),
                ('devices', models.ManyToManyField(to='core.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.FloatField()),
                ('date', models.CharField(default='', max_length=32)),
                ('contract', models.ManyToManyField(to='core.Contract')),
                ('person', models.ManyToManyField(to='core.Person')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(default='', max_length=256)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=256)),
                ('content', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('title', 'author')]),
        ),
        migrations.AddField(
            model_name='activity',
            name='detection_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='bookshelfentry',
            unique_together=set([('user', 'book')]),
        ),
    ]
