# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('lfd_id', models.CharField(blank=True, max_length=12)),
                ('parent_lfd_id', models.CharField(blank=True, max_length=12)),
                ('pnr_nr', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(blank=True, max_length=12)),
                ('given_name', models.CharField(blank=True, max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('email_address', models.CharField(blank=True, max_length=256)),
                ('browser_user_agent', models.CharField(blank=True, max_length=512)),
                ('telephone_number', models.CharField(blank=True, max_length=64)),
                ('telephone_country_code', models.CharField(blank=True, max_length=12)),
                ('birthday', models.CharField(blank=True, max_length=24)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('tropical_zodiac', models.CharField(blank=True, max_length=64)),
                ('cc_type', models.CharField(blank=True, max_length=64)),
                ('cc_number', models.CharField(blank=True, max_length=64)),
                ('cvv2', models.CharField(blank=True, max_length=12)),
                ('cc_expires', models.CharField(blank=True, max_length=64)),
                ('occupation', models.CharField(blank=True, max_length=256)),
                ('company', models.CharField(blank=True, max_length=256)),
                ('vehicle', models.CharField(blank=True, max_length=256)),
                ('domain', models.CharField(blank=True, max_length=256)),
                ('blood_type', models.CharField(blank=True, max_length=12)),
                ('pounds', models.CharField(blank=True, max_length=12)),
                ('kilograms', models.CharField(blank=True, max_length=12)),
                ('feet_inches', models.CharField(blank=True, max_length=12)),
                ('centimeters', models.CharField(blank=True, max_length=3)),
                ('profile_picture', models.CharField(blank=True, max_length=512)),
                ('maried', models.CharField(blank=True, max_length=64)),
                ('kids', models.CharField(blank=True, max_length=12)),
                ('income', models.CharField(blank=True, max_length=64)),
                ('expenses', models.CharField(blank=True, max_length=64)),
                ('fitness', models.CharField(blank=True, max_length=128)),
                ('activities', models.CharField(blank=True, max_length=512)),
                ('home_town', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('education', models.CharField(blank=True, max_length=256)),
                ('devices', models.CharField(blank=True, max_length=512)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'abstract': False,
                'verbose_name': 'user',
            },
        ),
    ]
