# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(default='', max_length=256)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
