# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionreason',
            name='href_fb_post',
        ),
        migrations.AddField(
            model_name='detectionreason',
            name='type',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='person',
            name='family_members',
            field=models.ManyToManyField(to='core.FamilyMember'),
        ),
        migrations.AddField(
            model_name='person',
            name='injuries',
            field=models.ManyToManyField(to='core.Injury'),
        ),
        migrations.AddField(
            model_name='person',
            name='lifestyle_entities',
            field=models.ManyToManyField(to='core.LifestyleEntity'),
        ),
        migrations.AddField(
            model_name='person',
            name='locations',
            field=models.ManyToManyField(to='core.Location'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='activities',
        ),
        migrations.AddField(
            model_name='person',
            name='activities',
            field=models.ManyToManyField(to='core.Activity'),
        ),
        migrations.AlterField(
            model_name='salarymapping',
            name='salary',
            field=models.CharField(default='', max_length=32),
        ),
    ]
