# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='nb_con',
        ),
        migrations.AddField(
            model_name='person',
            name='nb_con1',
            field=models.ManyToManyField(blank=True, related_name='nb_conn1', to='core.Contract'),
        ),
        migrations.AddField(
            model_name='person',
            name='nb_con2',
            field=models.ManyToManyField(blank=True, related_name='nb_conn2', to='core.Contract'),
        ),
        migrations.AddField(
            model_name='person',
            name='nb_con3',
            field=models.ManyToManyField(blank=True, related_name='nb_conn3', to='core.Contract'),
        ),
        migrations.AddField(
            model_name='person',
            name='nb_con4',
            field=models.ManyToManyField(blank=True, related_name='nb_conn4', to='core.Contract'),
        ),
        migrations.AddField(
            model_name='person',
            name='nb_p4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nb_p44', to='core.Person'),
        ),
    ]
