# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(default='', max_length=512),
        ),
    ]
