# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='activities',
        ),
        migrations.AddField(
            model_name='person',
            name='activities',
            field=models.ManyToManyField(blank=True, to='core.Activity'),
        ),
    ]
