# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('frequency', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href_to_image', models.CharField(default='', max_length=1024)),
                ('text', models.CharField(default='', max_length=512)),
                ('date', models.CharField(default='', max_length=32)),
                ('fb_post', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price', models.CharField(default='', max_length=32)),
                ('type', models.CharField(default='', max_length=256)),
                ('icon', models.CharField(default='', max_length=256)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('age', models.CharField(default='', max_length=12)),
                ('gender', models.CharField(default='', max_length=32)),
                ('relation', models.CharField(default='', max_length=64)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=32)),
                ('type', models.CharField(default='', max_length=128)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('frequency', models.CharField(default='', max_length=64)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('example_image', models.CharField(default='', max_length=1024)),
                ('detection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(default='', max_length=256)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='fb_access_token',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.RemoveField(
            model_name='person',
            name='devices',
        ),
        migrations.AddField(
            model_name='activity',
            name='detection_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason'),
        ),
        migrations.AddField(
            model_name='person',
            name='devices',
            field=models.ManyToManyField(to='core.Device'),
        ),
    ]
