# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookshelfEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=31)),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(default='', max_length=128)),
                ('start_date', models.CharField(default='', max_length=128)),
                ('end_date', models.CharField(default='', max_length=128)),
                ('contract_type', models.CharField(default='', max_length=128)),
                ('contract_class', models.CharField(default='', max_length=128)),
                ('due_data', models.CharField(default='', max_length=128)),
                ('amount_money', models.CharField(default='', max_length=128)),
                ('auto_extensions', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('name_url', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfd_id', models.CharField(blank=True, max_length=12)),
                ('parent_lfd_id', models.CharField(blank=True, max_length=12)),
                ('pnr_nr', models.CharField(blank=True, max_length=12)),
                ('title', models.CharField(blank=True, max_length=12)),
                ('given_name', models.CharField(blank=True, max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('gender', models.CharField(blank=True, max_length=32)),
                ('email_address', models.CharField(blank=True, max_length=256)),
                ('browser_user_agent', models.CharField(blank=True, max_length=512)),
                ('telephone_number', models.CharField(blank=True, max_length=64)),
                ('telephone_country_code', models.CharField(blank=True, max_length=12)),
                ('birthday', models.CharField(blank=True, max_length=24)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('tropical_zodiac', models.CharField(blank=True, max_length=64)),
                ('cc_type', models.CharField(blank=True, max_length=64)),
                ('cc_number', models.CharField(blank=True, max_length=64)),
                ('cvv2', models.CharField(blank=True, max_length=12)),
                ('cc_expires', models.CharField(blank=True, max_length=64)),
                ('occupation', models.CharField(blank=True, max_length=256)),
                ('company', models.CharField(blank=True, max_length=256)),
                ('vehicle', models.CharField(blank=True, max_length=256)),
                ('domain', models.CharField(blank=True, max_length=256)),
                ('blood_type', models.CharField(blank=True, max_length=12)),
                ('pounds', models.CharField(blank=True, max_length=12)),
                ('kilograms', models.CharField(blank=True, max_length=12)),
                ('feet_inches', models.CharField(blank=True, max_length=12)),
                ('centimeters', models.CharField(blank=True, max_length=3)),
                ('profile_picture', models.CharField(blank=True, max_length=512)),
                ('maried', models.CharField(blank=True, max_length=64)),
                ('kids', models.CharField(blank=True, max_length=12)),
                ('income', models.CharField(blank=True, max_length=64)),
                ('expenses', models.CharField(blank=True, max_length=64)),
                ('fitness', models.CharField(blank=True, max_length=128)),
                ('activities', models.CharField(blank=True, max_length=512)),
                ('home_town', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('education', models.CharField(blank=True, max_length=256)),
                ('devices', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
