# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='detection_reason',
        ),
    ]
