# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_familymember_detection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='detection_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason'),
        ),
        migrations.AlterField(
            model_name='device',
            name='detection_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason'),
        ),
        migrations.AlterField(
            model_name='injury',
            name='detection_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason'),
        ),
        migrations.AlterField(
            model_name='lifestyleentity',
            name='detection_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason'),
        ),
        migrations.AlterField(
            model_name='location',
            name='detection_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DetectionReason'),
        ),
    ]
