# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171007_1840'),
        ('core', '0002_auto_20171007_2031'),
    ]

    operations = [
    ]
