# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171007_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionreason',
            old_name='fb_post',
            new_name='href_fb_post',
        ),
    ]
