# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171007_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
