# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171007_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='person',
        ),
        migrations.RemoveField(
            model_name='device',
            name='person',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='person',
        ),
        migrations.RemoveField(
            model_name='injury',
            name='person',
        ),
        migrations.RemoveField(
            model_name='lifestyleentity',
            name='person',
        ),
        migrations.RemoveField(
            model_name='location',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='activities',
            field=models.ManyToManyField(blank=True, to='core.Activity'),
        ),
        migrations.AddField(
            model_name='person',
            name='devices',
            field=models.ManyToManyField(to='core.Device'),
        ),
        migrations.AddField(
            model_name='person',
            name='family_members',
            field=models.ManyToManyField(to='core.FamilyMember'),
        ),
        migrations.AddField(
            model_name='person',
            name='injuries',
            field=models.ManyToManyField(to='core.Injury'),
        ),
        migrations.AddField(
            model_name='person',
            name='lifestyle_entities',
            field=models.ManyToManyField(to='core.LifestyleEntity'),
        ),
        migrations.AddField(
            model_name='person',
            name='locations',
            field=models.ManyToManyField(to='core.Location'),
        ),
    ]
