# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-07 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171007_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='person',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='person',
            name='family_members',
        ),
        migrations.RemoveField(
            model_name='person',
            name='injuries',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lifestyle_entities',
        ),
        migrations.RemoveField(
            model_name='person',
            name='locations',
        ),
        migrations.AddField(
            model_name='familymember',
            name='per',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person'),
        ),
    ]
